### ISSUE TITLE
Add external libraries 

### ISSUE THREAD

**Issue by KaynNoNakka** [mobibean/codesnack-ide-feature-requests#11]
Please add external libraries

**Comment by bushev** [comment]
Hey @KaynNoNakka,

It's already possible to customize the execution container and add any external library using the`.config.xml` file.

Check out the example of how to install the `requests` Python module. Absolutely the same approach can be used for any other project where you need dependencies. Just install what do you need on the `prepare` step with a regular Linux command.

![IMG_1180](https://user-images.githubusercontent.com/7535766/117333841-5708ef80-ae67-11eb-9a41-4e5cf1d0f813.PNG)

**Comment by KaynNoNakka** [comment]
Oh, thanks for answering me, I'm starting now in the programming area and I
was looking for an "IDE" with good features for mobile devices and yours
interested me, I thank you in advance

Em 6 de mai de 2021 1:36 PM, "Yury Bushev" ***@***.***>
escreveu:
