### ISSUE TITLE
improve css editor

### ISSUE THREAD

**Issue by ghost** [mobibean/codesnack-ide-feature-requests#14]
**Is your feature request related to a problem? Please describe.**

no it’s not a problem

**Describe the solution you'd like**

auto complete for css for the ‘:’ and the ‘;’ instead of typing it manually

**Describe alternatives you've considered**

**Additional context**

**Comment by bushev** [comment]
Hey @NotFlawffles,

Thanks for the feature request!

This ticket is merged into the main one: https://github.com/mobibean/codesnack-ide-feature-requests/issues/3#issuecomment-831393931
