### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by Gnaneshwar-ux** [mobibean/codesnack-ide-feature-requests#15]
**Is your feature request related to a problem? Please describe.**
App and compilation of programs is too slow . I have like when I installed app but while using I understand it's too slow .so please 🥺 improve speed of application. And one more is console coming in middle of screen while using editor.

**Describe the solution you'd like**
 I want high compilation speed for free or atleast 2x for free

**Describe alternatives you've considered**
 Please update the app with more features and speed interface.

**Additional context**
App is running too slow provide updates faster and improve app interface some more

**Comment by bushev** [comment]
Hey @Gnaneshwar-ux,

It would be great if you can share what exactly you are trying to run. Very often project run speed can be improved by configuring the container's caching.

Could you please share your project's container and run configurations?
