### ISSUE TITLE
CSS highlighting & autocompleting broke

### ISSUE THREAD

**Issue by NotFlawffles** [mobibean/codesnack-ide-feature-requests#20]
![image](https://user-images.githubusercontent.com/76492813/118803756-6d259f80-b8ac-11eb-9577-2094493c96dd.jpeg)
it's not showing autocompleting things since the last update

**Comment by bushev** [comment]
CSS/HTML completion is in progress - https://github.com/mobibean/codesnack-ide-feature-requests/issues/3#issuecomment-831393931
