### ISSUE TITLE
Open Code From Files

### ISSUE THREAD

**Issue by MidKnighto** [mobibean/codesnack-ide-feature-requests#43]
Number 1; love your app and how its free to do pretty much everything, and the things that aren't free can be unlocked with a very cheap subscription!

Number 2; i think it would be very useful for the app to be able code from the devices file system. Just like the app can export files.

If you are readings this, i really appreciate your work! Thank you!

**Comment by bushev** [comment]
Hey, thanks a lot! ❤️

2. The app initially had the File import feature, but it's hidden currently because of unstable work after our core dependency upgrade (we are using Capacitor). I hope to get it back soon.

**Comment by MidKnighto** [comment]
Ah i see! Thank you so much for responding! I hope to see it implemented soon as well!

**Comment by bushev** [comment]
Hey @MidKnighto, the import file feature is back! Released yesterday.
