### ISSUE TITLE
Smaller fonts in the IDE

### ISSUE THREAD

**Issue by MFDaus47** [mobibean/codesnack-ide-feature-requests#46]
The font was way too big and it is problematic to always scroll sideways even for a code that is not even that long on a phone. You could also probably choose a font that's not too big in wideness.

**Comment by bushev** [comment]
Hey @MFDaus47,

Could you please try to change the font size here?

![image](https://user-images.githubusercontent.com/7535766/121981190-35026700-cd5b-11eb-9d82-f252dcb352be.png)

The feature request for the font already on the roadmap: https://github.com/mobibean/codesnack-ide-feature-requests/issues/25

**Comment by MFDaus47** [comment]
I did do that. However, I don't think it changed that much for me. It's maybe just because of my phone screen size. If you think you could lower it a little without affteing other phones or tablet, than that's great. But If it's going to create more issues, just tell me, and I'll close this request. Keep up the good work🙏

**Comment by MFDaus47** [comment]
> Hey @MFDaus47,
> 
> Could you please try to change the font size here?
> 
> ![image](https://user-images.githubusercontent.com/7535766/121981190-35026700-cd5b-11eb-9d82-f252dcb352be.png)
> 
> ---
> 
> The feature request for the font is already on the roadmap: https://github.com/mobibean/codesnack-ide-feature-requests/issues/25

Dude, I'm so sorry man. Just discovered that you could press that this multiple times and it will get smaller the more you press it. That's a brilliant idea, i don't know why I never noticed this. Sorry
