### ISSUE TITLE
Image request - Maven + Java 8

### ISSUE THREAD

**Issue by fermatjen** [mobibean/codesnack-ide-feature-requests#49]
Most of the Apache libraries work only on Java 8/Java 11. The Maven container image has the bleeding edge Java 16, which is the latest JDK but is still not supported for many real word projects. Is there any way we can have a custom image containing Maven tools + Java 8?

**Comment by bushev** [comment]
Hello @fermatjen,

The following maven Docker images were added:

```
maven:3-openjdk-17
maven:3-openjdk-16
maven:3-openjdk-15
maven:3-openjdk-14
maven:3-openjdk-11
maven:3-openjdk-8
```

Please restart the app. After the restart, you can change the container image as shown below:

![Frame 1](https://user-images.githubusercontent.com/7535766/122967556-924c7880-d358-11eb-9e8f-5f65b485f615.png)
