### ISSUE TITLE
Would Like an option to turn the autocorrect/intellisense off

### ISSUE THREAD

**Issue by NeonSupernova** [mobibean/codesnack-ide-feature-requests#55]
So, one particular problem Ive been having is due to the enormous heating of my phone, which I'm assuming is due to the cpu overheating or the battery, and one way I think this app could be better is a setting that would allow the code Intellisense to be turned off. I could just get a more simple Text Editor, but I like this one and want to support it.

**Comment by bushev** [comment]
Hey @NeonSupernova,

Fortunately, it's already here. Please, check out the new Settings options.

![IMG_2501](https://user-images.githubusercontent.com/7535766/124399312-89f52580-dce8-11eb-9d8b-75349e8e5688.jpg)
