### ISSUE TITLE
Add C++ external header files feature

### ISSUE THREAD

**Issue by DrTempoville** [mobibean/codesnack-ide-feature-requests#63]
Hi, I'm a new CodeSnack IDE user, and I love it so well! 
The feature I want to request is that I want you to add C++ external header files usage. Like we have a whole lot of header files for C++ rather than just the standard ones, for example graphics.h. So it'd be epic if you'd add that.

**Comment by bushev** [comment]
Hey @DrTempoville,

Thank you for the request!

The good news is that you can add any customization for the execution container by yourself. This means you can install any additional Linux libs. The program compilation command is also fully customizable, so you can add any library to the linker.

But be aware, CodeSnack IDE doesn't support GUI apps at this moment. Please thumbs up here if you like us to add this feature: https://github.com/mobibean/codesnack-ide-feature-requests/issues/12

![image](https://user-images.githubusercontent.com/7535766/130613788-163a1b9e-333f-4207-bc47-e230e495b92d.png)

![image](https://user-images.githubusercontent.com/7535766/130613866-e8d132ef-301c-4417-8ec1-57051adafdf5.png)
