### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by helloworld-foo-bar** [mobibean/codesnack-ide-feature-requests#69]
i would like to be able to access settings without opening a project.

**Comment by bushev** [comment]
Hey @helloworld-foo-bar,

Could you please describe a little more, what setting are you changing outside the project?

**Comment by helloworld-foo-bar** [comment]
Well when i open a project in the app i can access the font-family and more in settings, but when i close a project i can't access settings anymore.

**Comment by bushev** [comment]
Curious, what exactly are you trying to change in Settings while you are not in the Project?

**Comment by helloworld-foo-bar** [comment]
Sorry I accidentally close the issue￼

**Comment by helloworld-foo-bar** [comment]
I remember trying to access a setting and be annoyed that I had to create a project to access settings￼

**Comment by bushev** [comment]
Got it, most of the settings are project-related or workspace-related and it will be weird to move them outside of the project. That's why I'm asking about what settings exactly are you looking to move to the upper app level.

**Comment by bushev** [comment]
Settings now are moved to the 4th tab in a bottom tab bar.
