### ISSUE TITLE
BASH

### ISSUE THREAD

**Issue by tjgeirk** [mobibean/codesnack-ide-feature-requests#75]
Bash scripting would put this over all the rest

**Comment by bushev** [comment]
Hey,

Fortunately, the app has a Shell project template. It's where a bash scripting begins.

Enjoy!

![image](https://user-images.githubusercontent.com/7535766/133911138-ebfa38d1-b4e3-46fe-afb4-6579cfe0e173.jpeg)

![image](https://user-images.githubusercontent.com/7535766/133911146-b3732954-d665-4487-ba08-b5ba3d7b1151.png)
